### ISSUE TITLE
404 (Not Found) for background image in scss

### ISSUE THREAD

**Issue by devism** [cferdinandi/gulp-boilerplate#101]
I get a 404 not found when trying to reference a background image in scss. 

.call-to-action{
	background-image: url("../../copy/image11.png");
	background-repeat: none;
}

http://localhost:3002/copy/image11.png

**Comment by cferdinandi** [comment]
Sounds like the path to your image is wrong. I don't think that's a Gulp/boilerplate problem, though.

**Comment by devism** [comment]
Can you give me an example of how the path should be for an image that's in the `copy` folder when referencing it from `sass/components/_base.scss` ?  I tried multiple different paths and none seemed to work. Thank you

**Comment by cferdinandi** [comment]
The location should be your output location, not your input. Things in the `copy` directory get output as-is, directly into `dist`.

You *probably* want something like this?

```css
.call-to-action{
	background-image: url("../image11.png");
	background-repeat: none;
}
```
