### ISSUE TITLE
Not able to change "copy" folder name

### ISSUE THREAD

**Issue by shashwattiwari** [cferdinandi/gulp-boilerplate#102]
I was wondering if I can follow a different naming convention for my folder structure but unfortunately it's not working.

<pre>
Cannot GET /
</pre>

**Comment by cferdinandi** [comment]
Hi all, I'm not longer maintaining this project, and recommend you instead use my [Build Tool Boilerplate](https://github.com/cferdinandi/build-tool-boilerplate).
