### ISSUE TITLE
How to include js assets from vendor?

### ISSUE THREAD

**Issue by marvinhinz** [cferdinandi/gulp-boilerplate#103]
Im not really sure how to embed vendor js assets. For example bootstrap default js remains in node_modules, is there a proper way to include these? I dont see another way than manually copying these files. Maybe an additional copy config file could be useful?

**Comment by cferdinandi** [comment]
Hi there, this repo is largely unmaintained (I'll go update the readme now to reflect that).

I'd recommend checking out my new build tool boilerplate instead: https://github.com/cferdinandi/build-tool-boilerplate
