### ISSUE TITLE
Phantomjs peer dependency

### ISSUE THREAD

**Issue by danrichman** [cferdinandi/gulp-boilerplate#43]
Since the karma-phantomjs-launcher is a plugin for phantomjs you may want to add "phantomjs" as a devDependency. Because of this plugin/peer relationship npm>=3 prints a warning with during "npm install" with

```"npm WARN EPEERINVALID karma-phantomjs-launcher@0.2.1 requires a peer of phantomjs@>=1.9 but none was installed."```

This could be confusing for some developers.

**Comment by cferdinandi** [comment]
@danrichman You're absolutely right. Thanks! Will update.

**Comment by cferdinandi** [comment]
Addressed in v4.0.0
