### ISSUE TITLE
Browsersync

### ISSUE THREAD

**Issue by niallobrien** [cferdinandi/gulp-boilerplate#46]
Would you be open to adding Browsersync to this boilerplate? Thanks in advance.

**Comment by cferdinandi** [comment]
Hey there - I'd actually not heard of Browsersync prior to this, but YES! I'm very open to it. It looks to be a better Livereload.

Any interest in creating a PR? I'm assuming you'd remove LiveReload and replace it with Browsersync?

**Comment by niallobrien** [comment]
https://github.com/cferdinandi/gulp-boilerplate/pull/47

**Comment by cferdinandi** [comment]
I revisited this today and discovered that BrowserSync is broken on Windows. I think I'm going to close this out as "livereload is good enough."
