### ISSUE TITLE
Img directory

### ISSUE THREAD

**Issue by Allenivesix** [cferdinandi/gulp-boilerplate#49]
Hello, 
i have a problem with this directory, in your boilerplate i don't have any img directory, and when i try to create img directory the task delete it.   

in DIST i have  
     - CSS
     - JS
    -  SVG

how can fix this bug?

**Comment by cferdinandi** [comment]
Looking into this right now. Will let you know once it's fixed. Sorry!

**Comment by cferdinandi** [comment]
This will be addressed by https://github.com/cferdinandi/gulp-boilerplate/pull/50, which I'll be merging as soon as the tests are done running...

**Comment by cferdinandi** [comment]
This should now be addressed with the latest version. Please update.

**Comment by cferdinandi** [comment]
And thanks for letting me know!
