### ISSUE TITLE
Script concatenation question

### ISSUE THREAD

**Issue by nickpish** [cferdinandi/gulp-boilerplate#74]
First off- thank you for releasing this boilerplate, it's fantastic! I have a general question regarding how best to handle the concatenation of scripts w/ dependencies: let's say, for instance, I'm using a library like `fullPage.js`, and I have a separate script, e.g. `init.js` with the various initialization settings, and I'd like to ultimately output a single, concatenated js file (starting w/ the lib file, followed by the init) into the `dist` folder- can I easily configure this sort of thing using your boilerplate? Thanks for any guidance here.

**Comment by cferdinandi** [comment]
On my project, I drop those into a single directory. My inits go into a file named `zzz_inits.js` to force it to show up at the end.

**Comment by nickpish** [comment]
Ok- thanks for the prompt reply!
