### ISSUE TITLE
gulp-cssnano deprecated for cssnano

### ISSUE THREAD

**Issue by adam-hite** [cferdinandi/gulp-boilerplate#78]
Looks like [gulp-cssnano](https://github.com/ben-eb/gulp-cssnano) is now deprecated and recommends using [cssnano](https://github.com/cssnano/cssnano) via PostCSS instead. I am getting npm audit vulnerabilities:

> Package: js-yaml
> Patched in: >=3.13.0
> Dependency of: gulp-cssnano [dev]
> Path: gulp-cssnano > cssnano > postcss-svgo > svgo > js-yaml
> More info: https://npmjs.com/advisories/788
> 
> High: Code Injection
> Package: js-yaml
> Patched in: >=3.13.1
> Dependency of: gulp-cssnano [dev]
> Path: gulp-cssnano > cssnano > postcss-svgo > svgo > js-yaml
> More info: https://npmjs.com/advisories/813

**Comment by cferdinandi** [comment]
Sigh... I hate maintaining dependencies. Thanks!

**Comment by cferdinandi** [comment]
Fixed with v2.2.4. Thanks Adam!
