### ISSUE TITLE
Add gulp-babel to compile ES6 to ES5 by default

### ISSUE THREAD

**Issue by tomhrtly** [cferdinandi/gulp-boilerplate#79]
Would you be able to add the `gulp-babel` plugin so that by default, all JavaScript is compiled from ES6 to ES5 or provide an example of how to do so?

I've tried adding this myself but when running `gulp`, I just get warnings in the Terminal about using ES6 syntax. The JavaScript compiles but the ES6 syntax is in the distributed file.

Thanks for this great boilerplate!

**Comment by cferdinandi** [comment]
No babel by default, but I do need to update from js-uglify, which is only ES5 and below compatible and no longer supported by it's developer.

terser is a fork that uses the same syntax but supports ES6.

**Comment by cferdinandi** [comment]
This has been updated to Terser, which should solve the ES6 issues.
