### ISSUE TITLE
Gulp Header Bug

### ISSUE THREAD

**Issue by eclectic-coding** [cferdinandi/gulp-boilerplate#85]
Chris,
I have a noticed that the minified CSS file includes both the `full` and `min` banners. The problem is this section of the code in the gulp file is not working properly:
```
.pipe(postcss([
			minify({
				discardComments: {
					removeAll: true
				}
			})
		]))
```
I ended up using the package `gulp-strip-css-comments` and replacing the above code with:
```
var strip = require('gulp-strip-css-comments')

.pipe(strip({ preserve: false }))
```

**Comment by cferdinandi** [comment]
Fixed with v2.2.5. All files now get only the skinny banner. `cssnano` refuses to strip out special comments (ones prefixed with a `!`) as they're often used for licensing information.
