### ISSUE TITLE
Browsersync: Inject styles with stream

### ISSUE THREAD

**Issue by viktorbijlenga** [cferdinandi/gulp-boilerplate#86]
Browsersync have support to auto inject styles though streams, instead of only using reload. Would it be possible to add support for this?

https://www.browsersync.io/docs/gulp#gulp-sass-css

**Comment by cferdinandi** [comment]
I'm happy to entertain a pull request if you wanted to put one together.

**Comment by viktorbijlenga** [comment]
I would love to contribute, but I could need some pointers to get it done right. Anyone willing to help me out?

**Comment by cferdinandi** [comment]
Hi all, I'm not longer maintaining this project, and recommend you instead use my [Build Tool Boilerplate](https://github.com/cferdinandi/build-tool-boilerplate).
