### ISSUE TITLE
Add images task

### ISSUE THREAD

**Issue by florianbouvot** [cferdinandi/gulp-boilerplate#92]
Hi @cferdinandi, 

What about adding a task to copy and optimize images?

Florian.

**Comment by trinkel** [comment]
Upvote.

I think this would be an excellent addition to this boilerplate

Tim

**Comment by cferdinandi** [comment]
I should add a note to the README that this is not really a project I'm taking feature requests or anything on. As a boilerplate, the idea is that you can add your own spin on it and bolt-in whatever you need.

I've also been using favoring more "close to the metal" build tools lately: https://github.com/cferdinandi/build-tool-boilerplate

**Comment by trinkel** [comment]
Thanks Chris. I was just thinking last night about how all the dependencies were turning into a real pain. I’ll definitely give the build-tool a shot.

Tim

**Comment by cferdinandi** [comment]
Same! Gulp is awesome, but I got so sick of managing the massive number of dependencies, and all the security warnings that seem to go along with it.

My newer boiler plate still has dependencies, of course, but it’s a lot more lean and mean, which is my preferred development style.
