### ISSUE TITLE
Autoprefixer configuration

### ISSUE THREAD

**Issue by innomerphey** [cferdinandi/gulp-boilerplate#93]
Hello, I just noticed that the default settings are used for the autoprefixer configuration.

` .pipe(postcss([
      prefix({
        cascade: true,
        remove: true
      })
    ]))`

> cascade (boolean): should Autoprefixer use Visual Cascade, if CSS is uncompressed. Default: true
...
remove (boolean): should Autoprefixer [remove outdated] prefixes. Default is true.

**Comment by cferdinandi** [comment]
Hi all, I'm not longer maintaining this project, and recommend you instead use my [Build Tool Boilerplate](https://github.com/cferdinandi/build-tool-boilerplate).
